name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  

    - name: Replace tokens
      # You may pin to the exact commit or the version.
      # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
      uses: cschleiden/replace-tokens@v1.2
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["**/*.cs"]'
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    
    - name: .Net Build
      uses: EasyDesk/action-dotnet-build@v1.0.0
    
    - name: ftp-action-copy-to-serverstarter.host
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ${{ secrets.SERVERSTARTER_FTP_HOST }}
        user: ${{ secrets.SERVERSTARTER_FTP_USERNAME }}
        password: ${{ secrets.SERVERSTARTER_FTP_PASSWORD }}
        local_dir: ./bin/Release/net6.0
        delete: true
        ftp_ssl_allow: true
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        tags: alessiofilippin/sinner-bot:latest
        push: ${{ github.ref == 'refs/heads/main' }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
