name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  

    - name: Replace tokens
      # You may pin to the exact commit or the version.
      # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
      uses: cschleiden/replace-tokens@v1.2
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["**/*.cs"]'
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    
    - name: .Net Build
      uses: EasyDesk/action-dotnet-build@v1.0.0
    
    - name: SFTP Upload Code to hosting
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:			 
       host: ${{ secrets.SERVERSTARTER_FTP_HOST }}
       port: 2022
       username: ${{ secrets.SERVERSTARTER_FTP_USERNAME }}
       password: ${{ secrets.SERVERSTARTER_FTP_PASSWORD }}
       localDir: ./bin/Release/net6.0
       forceUpload: true
       dryRun: false
